name: QA Automation CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Instalar dependências
        run: npm install

      - name: 🎭 Instalar browsers do Playwright
        run: npx playwright install --with-deps
      - name: 📁 Criar pasta reports
        run: mkdir -p reports

      # =========================
      # API TESTS
      # =========================
      - name: ⚙️ Rodar testes API
        run: npm run test:api
        continue-on-error: true

      # =========================
      # E2E TESTS
      # =========================
      - name: 🧪 Rodar testes E2E
        run: npm run test:e2e

      # =========================
      # PERFORMANCE (K6)
      # =========================
      - name: 🚀 Run K6 tests
        run: |
          curl -s https://dl.k6.io/key.gpg | sudo apt-key add -
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install k6
          k6 run performance/load-test.js --summary-export=reports/k6-summary.json

      # =========================
      # REPORTS
      # =========================
      - name: 📊 Gerar relatório HTML
        if: always()
        run: npm run report
      - name: 🎭 Gerar Playwright HTML report
        if: always()
        run: npx playwright show-report

      # =========================
      # ARTIFACTS
      # =========================
      - name: 📁 Upload relatório HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: reports/cucumber-report.html

      - name: 📁 Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: reports/
        
      - name: 📁 Upload evidências
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results/

      - name: 📈 Upload K6 report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: k6-report
          path: reports/k6-summary.json
      - name: 🧱 Criar dashboard index.html
        run: |
            mkdir -p reports
            echo '<!DOCTYPE html>
            <html>
            <head><title>QA Automation</title></head>
            <body>
            <h1>🚀 QA Automation Reports</h1>
            <a href="./cucumber-report.html">Cucumber</a><br>
            <a href="./playwright-report/index.html">Playwright</a><br>
            <a href="./k6-summary.json">K6</a>
            </body>
            </html>' > reports/index.html
      - name: 📂 Debug reports
        run: |
              echo "Conteúdo da pasta reports:"
              ls -R reports

  # =========================
  # DEPLOY GH PAGES
  # =========================
  deploy:
    needs: tests
    runs-on: ubuntu-latest
    if: always()

    permissions:
      contents: write

    steps:
    - name: 📥 Checkout
      uses: actions/checkout@v4

    - name: 📥 Download reports
      uses: actions/download-artifact@v4
      with:
        name: reports
        path: reports

    - name: 📂 Listar arquivos
      run: ls -R reports

    - name: 🚀 Deploy no GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./reports
        force_orphan: false